steps:
- name: 'node:latest'
  id: Perform Unit Tests
  entrypoint: /bin/sh
  args:
  - -c
  - 'cd app && npm install && npm test'

- name: 'gcr.io/cloud-builders/docker'
  id: Build Docker Image
  args:
  - 'build'
  - '-t'
  - 'gcr.io/cicd-fcamba/gcp-cnci-example-app:${SHORT_SHA}'
  - 'app/'